apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: posts-app
  template:
    metadata:
      labels:
        app: posts-app
    spec:
      containers:
        - name: posts-app-container
          image: sharukhvs/posts-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: posts-app-service
spec:
  selector:
    app: posts-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer